// Contracts: JSON output schemas for LLM Reason/Explore tasks.
// Validates that LLM output conforms to the expected structure before
// writing intents back to the graph.

use serde::{Deserialize, Serialize};
use std::fmt;

// ── Reason task output ──────────────────────────────────────────────────────

/// An intent generated by the Reason task.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntentSpec {
    /// IDs of facts this intent stems from.
    pub from: Vec<String>,
    /// Short title for the task.
    pub title: String,
    /// Detailed instruction for the executing agent.
    pub instruction: String,
}

/// Reason task completion signal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompleteRef {
    /// IDs of facts that satisfy the goal.
    pub from: Vec<String>,
    /// Human-readable explanation.
    pub description: String,
}

/// All valid output shapes from a Reason task.
///
/// The LLM must return exactly one of:
/// - `{"complete": {...}}` — goal is satisfied
/// - `{"intents": [...]}` — new intents to dispatch
/// - `{}` — no action needed (noop)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReasonOutput {
    Complete { complete: CompleteRef },
    Intents { intents: Vec<IntentSpec> },
    Noop {},
}

// ── Explore task output ─────────────────────────────────────────────────────

/// A fact produced by an Explore task.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FactSpec {
    /// IDs of intents this fact resolves.
    pub from: Vec<String>,
    /// Short key / slug for the fact.
    pub key: String,
    /// Full description of what was discovered.
    pub description: String,
    /// Confidence level: "confirmed" | "suspected" | "refuted"
    #[serde(default = "default_confidence")]
    pub confidence: String,
}

fn default_confidence() -> String {
    "confirmed".to_string()
}

/// All valid output shapes from an Explore task.
///
/// The LLM must return exactly one of:
/// - `{"fact": {...}}` — a new fact to write to the graph
/// - `{"blocked": "reason"}` — cannot proceed, needs more info
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExploreOutput {
    Fact { fact: FactSpec },
    Blocked { blocked: String },
}

// ── Validation ──────────────────────────────────────────────────────────────

#[derive(Debug)]
pub enum ContractError {
    Parse(serde_json::Error),
    TooManyIntents(usize),
    EmptyIntentTitle(usize),
    EmptyFromRefs(usize),
}

impl fmt::Display for ContractError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ContractError::Parse(e) => write!(f, "JSON parse error: {e}"),
            ContractError::TooManyIntents(n) => {
                write!(f, "reason output has too many intents: {n} > 5")
            }
            ContractError::EmptyIntentTitle(i) => {
                write!(f, "intent has empty title: index {i}")
            }
            ContractError::EmptyFromRefs(i) => {
                write!(f, "intent has empty 'from' refs: index {i}")
            }
        }
    }
}

impl std::error::Error for ContractError {}

impl From<serde_json::Error> for ContractError {
    fn from(e: serde_json::Error) -> Self {
        ContractError::Parse(e)
    }
}

/// Parse and validate a Reason task's raw LLM output string.
pub fn validate_reason_output(raw: &str) -> Result<ReasonOutput, ContractError> {
    let output: ReasonOutput = serde_json::from_str(raw)?;

    if let ReasonOutput::Intents { ref intents } = output {
        if intents.len() > 5 {
            return Err(ContractError::TooManyIntents(intents.len()));
        }
        for (i, intent) in intents.iter().enumerate() {
            if intent.title.trim().is_empty() {
                return Err(ContractError::EmptyIntentTitle(i));
            }
            if intent.from.is_empty() {
                return Err(ContractError::EmptyFromRefs(i));
            }
        }
    }

    Ok(output)
}

/// Parse and validate an Explore task's raw LLM output string.
pub fn validate_explore_output(raw: &str) -> Result<ExploreOutput, ContractError> {
    let output: ExploreOutput = serde_json::from_str(raw)?;
    Ok(output)
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reason_noop_parses() {
        let out = validate_reason_output("{}").unwrap();
        assert!(matches!(out, ReasonOutput::Noop {}));
    }

    #[test]
    fn reason_complete_parses() {
        let json = r#"{"complete": {"from": ["f-001"], "description": "goal met"}}"#;
        let out = validate_reason_output(json).unwrap();
        assert!(matches!(out, ReasonOutput::Complete { .. }));
    }

    #[test]
    fn reason_intents_parses() {
        let json =
            r#"{"intents": [{"from": ["f-001"], "title": "explore X", "instruction": "do it"}]}"#;
        let out = validate_reason_output(json).unwrap();
        assert!(matches!(out, ReasonOutput::Intents { .. }));
    }

    #[test]
    fn reason_too_many_intents_rejected() {
        let intent = r#"{"from": ["f-1"], "title": "t", "instruction": "i"}"#;
        let intents: Vec<&str> = vec![intent; 6];
        let json = format!(r#"{{"intents": [{}]}}"#, intents.join(","));
        let err = validate_reason_output(&json).unwrap_err();
        assert!(matches!(err, ContractError::TooManyIntents(6)));
    }

    #[test]
    fn reason_empty_title_rejected() {
        let json = r#"{"intents": [{"from": ["f-1"], "title": "  ", "instruction": "i"}]}"#;
        let err = validate_reason_output(&json).unwrap_err();
        assert!(matches!(err, ContractError::EmptyIntentTitle(0)));
    }

    #[test]
    fn reason_empty_from_rejected() {
        let json = r#"{"intents": [{"from": [], "title": "t", "instruction": "i"}]}"#;
        let err = validate_reason_output(&json).unwrap_err();
        assert!(matches!(err, ContractError::EmptyFromRefs(0)));
    }

    #[test]
    fn explore_fact_parses() {
        let json = r#"{"fact": {"from": ["i-001"], "key": "found-vuln", "description": "XSS in login form"}}"#;
        let out = validate_explore_output(json).unwrap();
        assert!(matches!(out, ExploreOutput::Fact { .. }));
    }

    #[test]
    fn explore_blocked_parses() {
        let json = r#"{"blocked": "cannot access target"}"#;
        let out = validate_explore_output(json).unwrap();
        assert!(matches!(out, ExploreOutput::Blocked { .. }));
    }

    #[test]
    fn invalid_json_returns_parse_error() {
        let err = validate_reason_output("not json").unwrap_err();
        assert!(matches!(err, ContractError::Parse(_)));
    }
}
